/*
 * adminsuccess.java
 *
 * Created on December 12, 2009, 3:17 AM
 */

package web;

/**
 *
 * @author  genius
 */
public class adminsuccess extends javax.swing.JFrame {
    
    /** Creates new form adminsuccess */
    public adminsuccess() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jrb1 = new javax.swing.JRadioButton();
        jrb2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jrb3 = new javax.swing.JRadioButton();
        jrb4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("admin success");
        setBackground(new java.awt.Color(102, 255, 153));
        setBounds(new java.awt.Rectangle(250, 250, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jrb1.setText("add a police station");
        jrb1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrb1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jrb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb1ActionPerformed(evt);
            }
        });

        jrb2.setText("upload a criminal's photo");
        jrb2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrb2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jrb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb2ActionPerformed(evt);
            }
        });

        jLabel1.setText("     ADMIN SUCCESS");

        jrb3.setText("customize home page contents");
        jrb3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrb3.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jrb4.setText("appoint DGP");
        jrb4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrb4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jrb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jrb1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jrb3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jrb4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jrb2)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jrb1)
                .addGap(33, 33, 33)
                .addComponent(jrb3)
                .addGap(29, 29, 29)
                .addComponent(jrb4)
                .addGap(41, 41, 41)
                .addComponent(jrb2)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb4ActionPerformed
// TODO add your handling code here:
       appointdgp ad = new appointdgp();
     ad.setTitle("Appoint A DGP");
     ad.setVisible(true);
     this.setVisible(false);   
    }//GEN-LAST:event_jrb4ActionPerformed

    private void jrb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb2ActionPerformed
// TODO add your handling code here:
    adminuploads ad = new adminuploads();
     ad.setTitle("upload a photo");
     ad.setVisible(true);
     this.setVisible(false);
    }//GEN-LAST:event_jrb2ActionPerformed

    private void jrb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb1ActionPerformed
// TODO add your handling code here:
     createps ps=new createps();
     ps.setVisible(true);
     this.setVisible(false);
    }//GEN-LAST:event_jrb1ActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminsuccess().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jrb1;
    private javax.swing.JRadioButton jrb2;
    private javax.swing.JRadioButton jrb3;
    private javax.swing.JRadioButton jrb4;
    // End of variables declaration//GEN-END:variables
    
}
